#!/bin/sh
#
# Description: Dummy init script for yadtreceiver.
#              You may want/need to modify this file to fit your needs.
#
# Author:      Michael Gruber <aelgru@gmail.com>


PIDFILE=/var/run/yadtreceiver.pid
TACFILE=/etc/twisted-taps/yadtreceiver.tac
TWISTD=/usr/bin/twistd
 
[ -r /etc/default/yadtshell-receiver ] && . /etc/default/yadtshell-receiver

check_twistd_exists() {
    if [ ! -x $TWISTD ]
    then
        echo "$TWISTD does not exist or is not executable."
        exit 1
    fi
}
 
check_pid_file_exists() {
    if [ ! -f $PIDFILE ]
    then
        echo "$PIDFILE does not exist."
        exit 1
    fi
}

start_daemon() {
    check_twistd_exists
    
    $TWISTD --pidfile=$PIDFILE --python=$TACFILE ${uid:+--uid=$uid} ${gid:+--gid=$gid}
}
 
stop_daemon() {
    check_pid_file_exists    
    kill -QUIT `cat $PIDFILE` && rm $PIDFILE
}

case "$1" in
    start)
        echo -n "Starting yadtreceiver... "
        start_daemon
        echo ""
    ;;
    stop)
        echo -n "Stopping yadtreceiver... "
        stop_daemon
        echo ""
    ;;
    restart)
        echo "Restarting yadtreceiver... "
        stop_daemon
        sleep 1
        start_daemon
    ;;
    *)
        echo "Usage: ${0} {start|stop|restart}" >&2
        exit 3
    ;;
esac
 
exit 0
